# test this file with
#   goreleaser release --config goreleaser.yml --clean --skip publish
version: 2
builds:
  - main: ./cmd/md
    binary: md
    env:
      - CGO_ENABLED=0
    flags:
      - -trimpath
    ldflags:
      - -s -w -X main.version={{.Version}}
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: windows
        goarch: arm
nfpms:
  - package_name: md
    maintainer: "https://github.com/{{ .Env.GITHUB_USER }}"
    formats:
      - deb
      - rpm
      - apk
archives:
  - name_template: "md_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    formats:
      - tar.gz
    format_overrides:
      - goos: windows
        formats:
          - zip
    files:
      - none*
changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
